<a href="https://colab.research.google.com/github/MdAshraf123/ML/blob/main/sentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, classification_report
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re
from nltk.tokenize import word_tokenize

In [ ]:
df=pd.read_csv('sentiment_analysis.csv')
df

,Year,Month,Day,Time of Tweet,text,sentiment,Platform
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook
2,2017,8,18,night,Don't angry me,negative,Facebook
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook
4,2022,6,8,noon,"Those who want to go, let them go",negative,Instagram
...,...,...,...,...,...,...,...
494,2015,10,18,night,"According to , a quarter of families under six...",negative,Twitter
495,2021,2,25,morning,the plan to not spend money is not going well,negative,Instagram
496,2022,5,30,noon,uploading all my bamboozle pictures of facebook,neutral,Facebook
497,2018,8,10,night,congratulations ! you guys finish a month ear...,positive,Twitter
498,2019,3,25,morning,"actually, I wish I was back in Tahoe. I miss...",negative,Instagram

In [ ]:
text= df[['text', 'sentiment']]

In [ ]:
text

                                                  text sentiment
0                What a great day!!! Looks like dream.  positive
1       I feel sorry, I miss you here in the sea beach  positive
2                                       Don't angry me  negative
3    We attend in the class just for listening teac...  negative
4                    Those who want to go, let them go  negative
..                                                 ...       ...
494  According to , a quarter of families under six...  negative
495      the plan to not spend money is not going well  negative
496    uploading all my bamboozle pictures of facebook   neutral
497   congratulations ! you guys finish a month ear...  positive
498   actually, I wish I was back in Tahoe.  I miss...  negative

[499 rows x 2 columns]

In [ ]:
data=text.sample(frac=1).reset_index(drop=True)
data

                                                  text sentiment
0    I tried to shtdown my pc and accenditenly I cl...  negative
1     was that sass I detect?  As long as it isn`t ...   neutral
2      That makes my day so much better, it`s been ...   neutral
3                                   i need coffee too.   neutral
4                               whats the day going on   neutral
..                                                 ...       ...
494   If only we could ever actually be allowed to ...   neutral
495                                     Don't angry me  negative
496                   Its raining, I need an umbrella    neutral
497   I make that same face when I get home and you...   neutral
498                 And to you too, how are you today?   neutral

[499 rows x 2 columns]

In [ ]:
x=data['text']
y=data['sentiment']

In [ ]:
nltk.download('stopwords')
en_english=stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
lowercase= x.str.lower().apply(lambda x: re.sub('[^\w\s]','',x))
lowercase

0      i tried to shtdown my pc and accenditenly i cl...
1       was that sass i detect  as long as it isnt ba...
2        that makes my day so much better its been a ...
3                                      i need coffee too
4                                 whats the day going on
                             ...
494     if only we could ever actually be allowed to ...
495                                        dont angry me
496                      its raining i need an umbrella
497     i make that same face when i get home and you...
498                     and to you too how are you today
Name: text, Length: 499, dtype: object

In [ ]:
no_stopwords= lowercase.apply(lambda x: ' '.join([ word for word in x.split() if word not in en_english]))
no_stopwords

0      tried shtdown pc accenditenly click restart bu...
1                   sass detect long isnt back sass haha
2      makes day much better rough one mention love n...
3                                            need coffee
4                                        whats day going
                             ...
494                     could ever actually allowed stay
495                                           dont angry
496                                raining need umbrella
497                make face get home mom watching soaps
498                                                today
Name: text, Length: 499, dtype: object

In [ ]:
countvec= CountVectorizer()
bow=countvec.fit_transform(no_stopwords).toarray()
bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
df=pd.DataFrame(bow, columns=countvec.get_feature_names_out())
df

,10,100,1130,140,15,1750,19,21,25,250,...,yesterday,yet,yor,youd,youll,youre,youtube,youve,yum,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
495,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
y

0      negative
1       neutral
2       neutral
3       neutral
4       neutral
         ...
494     neutral
495    negative
496     neutral
497     neutral
498     neutral
Name: sentiment, Length: 499, dtype: object

In [ ]:
X_train, X_test, y_train, y_test= train_test_split(df, y, test_size=0.2, random_state=42)

In [ ]:
model= LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
prediction= model.predict(X_test)

In [ ]:
prediction

array(['positive', 'neutral', 'neutral', 'positive', 'neutral', 'neutral',
       'neutral', 'neutral', 'negative', 'neutral', 'neutral', 'negative',
       'neutral', 'negative', 'neutral', 'neutral', 'negative', 'neutral',
       'negative', 'negative', 'positive', 'positive', 'negative',
       'positive', 'negative', 'negative', 'neutral', 'positive',
       'neutral', 'neutral', 'neutral', 'positive', 'neutral', 'positive',
       'neutral', 'neutral', 'neutral', 'positive', 'positive',
       'negative', 'neutral', 'neutral', 'neutral', 'neutral', 'negative',
       'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral',
       'positive', 'positive', 'positive', 'negative', 'positive',
       'neutral', 'neutral', 'neutral', 'positive', 'positive', 'neutral',
       'negative', 'neutral', 'positive', 'positive', 'negative',
       'neutral', 'negative', 'negative', 'negative', 'negative',
       'negative', 'neutral', 'positive', 'neutral', 'negative',
       'positive', 'neutral', 'neutral', 'neutral', 'neutral', 'negative',
       'neutral', 'positive', 'positive', 'neutral', 'positive',
       'neutral', 'positive', 'neutral', 'neutral', 'neutral', 'positive',
       'neutral', 'neutral', 'neutral', 'positive', 'neutral', 'neutral'],
      dtype=object)

In [ ]:
accuracy_score(prediction,y_test)

0.66

In [ ]:
print(classification_report(y_test, prediction,zero_division=0))

              precision    recall  f1-score   support

    negative       0.86      0.53      0.65        34
     neutral       0.58      0.84      0.69        37
    positive       0.65      0.59      0.62        29

    accuracy                           0.66       100
   macro avg       0.70      0.65      0.65       100
weighted avg       0.70      0.66      0.66       100

In [ ]:
t= countvec.transform(["i had an accident"])
t.toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [ ]:
result=model.predict(t.toarray())
result

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array(['neutral'], dtype=object)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
nb= MultinomialNB().fit(X_train, y_train)
nb_prediction= nb.predict(X_test)

In [ ]:
accuracy_score(y_test, nb_prediction)

0.6

In [ ]:
print(classification_report(y_test, nb_prediction,zero_division=0))

              precision    recall  f1-score   support

    negative       0.75      0.62      0.68        34
     neutral       0.57      0.62      0.60        37
    positive       0.50      0.55      0.52        29

    accuracy                           0.60       100
   macro avg       0.61      0.60      0.60       100
weighted avg       0.61      0.60      0.60       100

In [ ]:
nb.predict(t.toarray())

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(

array(['neutral'], dtype='<U8')

In [ ]:
from sklearn.linear_model import SGDClassifier

In [ ]:
svm= SGDClassifier().fit(X_train, y_train)## empty arguement of SGDClassifier() give us Linear SVM (support vector machine)
svm_prediction= svm.predict(X_test)

In [ ]:
accuracy_score(y_test,svm_prediction)

0.61